![display relevant image here](path/url/to/image)
- Banner/header image

# Financial Risk Modeling for Loan Approval
**Objective**
Building a reliable credit decision support model to predict whether a loan application should be approved.

## Overview
- BLUF (Bottom Line Up Front)
- One paragraph summary of final model performance and business implications
- Frame your 'story'

## Business Understanding

1. Begin by thoroughly analyzing the business context of FinTech Innovations' loan approval process. Write a short summary that:
- Describes the current manual process and its limitations
- Identifies key stakeholders and their needs
- Explains the implications of different types of model errors
- Justifies your choice between classification and regression approaches

2. Define your modeling goals and success criteria:
- Select appropriate evaluation metrics based on business impact
- You must use at least two different metrics
- Consider creating custom metric
- Establish baseline performance targets
- Document your reasoning for each choice

## Data Understanding
3. Conduct comprehensive exploratory data analysis:
- Describe basic data characteristics
- Examine distributions of all features and target variables
- Investigate relationships between features
- Create visualizations to help aid in EDA
- Document potential data quality issues and their implications

4. Develop feature understanding:
- Categorize features by type (numerical, categorical, ordinal)
- Identify features requiring special preprocessing
- Document missing value patterns and their potential meanings
- Note potential feature engineering opportunities

In [ ]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report, roc_auc_score, RocCurveDisplay

In [6]:
#Import the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve

# Optional: Suppress warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Loading Dataset
df=pd.read_csv('financial_loan_data.csv')
df.head()

   Age AnnualIncome  ...  LoanApproved RiskScore
0   45   $39,948.00  ...             0      49.0
1   38   $39,709.00  ...             0      52.0
2   47   $40,724.00  ...             0      52.0
3   58   $69,084.00  ...             0      54.0
4   37  $103,264.00  ...             1      36.0

[5 rows x 35 columns]

In [7]:
df.tail()

       Age AnnualIncome  ...  LoanApproved RiskScore
19995   44   $30,180.00  ...             0      55.0
19996   56   $49,246.00  ...             0      54.0
19997   44   $48,958.00  ...             0      45.0
19998   60   $41,025.00  ...             0      59.0
19999   20   $53,227.00  ...             0      59.0

[5 rows x 35 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         20000 non-null  int64
 1   AnnualIncome                20000 non-null  object
 2   CreditScore                 20000 non-null  int64
 3   EmploymentStatus            20000 non-null  object
 4   EducationLevel              19099 non-null  object
 5   Experience                  20000 non-null  int64
 6   LoanAmount                  20000 non-null  int64
 7   LoanDuration                20000 non-null  int64
 8   MaritalStatus               18669 non-null  object
 9   NumberOfDependents          20000 non-null  int64
 10  HomeOwnershipStatus         20000 non-null  object
 11  MonthlyDebtPayments         20000 non-null  int64
 12  CreditCardUtilizationRate   20000 non-null  float64
 13  NumberOfOpenCreditLines     20000 non-null  int64
 14  NumberOfCreditInquiries     20000 non-null  int64
 15  DebtToIncomeRatio           20000 non-null  float64
 16  BankruptcyHistory           20000 non-null  object
 17  LoanPurpose                 20000 non-null  object
 18  PreviousLoanDefaults        20000 non-null  int64
 19  PaymentHistory              20000 non-null  int64
 20  LengthOfCreditHistory       20000 non-null  int64
 21  SavingsAccountBalance       19428 non-null  float64
 22  CheckingAccountBalance      20000 non-null  int64
 23  TotalAssets                 20000 non-null  int64
 24  TotalLiabilities            20000 non-null  int64
 25  MonthlyIncome               20000 non-null  float64
 26  UtilityBillsPaymentHistory  20000 non-null  float64
 27  JobTenure                   20000 non-null  int64
 28  NetWorth                    20000 non-null  int64
 29  BaseInterestRate            20000 non-null  float64
 30  InterestRate                20000 non-null  float64
 31  MonthlyLoanPayment          20000 non-null  float64
 32  TotalDebtToIncomeRatio      20000 non-null  float64
 33  LoanApproved                20000 non-null  int64
 34  RiskScore                   20000 non-null  float64
dtypes: float64(10), int64(18), object(7)
memory usage: 5.3+ MB

In [8]:
df.describe()

                Age   CreditScore  ...  LoanApproved     RiskScore
count  20000.000000  20000.000000  ...  20000.000000  20000.000000
mean      39.752600    571.612400  ...      0.239000     50.766780
std       11.622713     50.997358  ...      0.426483      7.778262
min       18.000000    343.000000  ...      0.000000     28.800000
25%       32.000000    540.000000  ...      0.000000     46.000000
50%       40.000000    578.000000  ...      0.000000     52.000000
75%       48.000000    609.000000  ...      0.000000     56.000000
max       80.000000    712.000000  ...      1.000000     84.000000

[8 rows x 28 columns]

In [9]:
# Check column names
print(df.columns)

Index(['Age', 'AnnualIncome', 'CreditScore', 'EmploymentStatus',
       'EducationLevel', 'Experience', 'LoanAmount', 'LoanDuration',
       'MaritalStatus', 'NumberOfDependents', 'HomeOwnershipStatus',
       'MonthlyDebtPayments', 'CreditCardUtilizationRate',
       'NumberOfOpenCreditLines', 'NumberOfCreditInquiries',
       'DebtToIncomeRatio', 'BankruptcyHistory', 'LoanPurpose',
       'PreviousLoanDefaults', 'PaymentHistory', 'LengthOfCreditHistory',
       'SavingsAccountBalance', 'CheckingAccountBalance', 'TotalAssets',
       'TotalLiabilities', 'MonthlyIncome', 'UtilityBillsPaymentHistory',
       'JobTenure', 'NetWorth', 'BaseInterestRate', 'InterestRate',
       'MonthlyLoanPayment', 'TotalDebtToIncomeRatio', 'LoanApproved',
       'RiskScore'],
      dtype='object')

In [11]:
df.dtypes

Age                             int64
AnnualIncome                   object
CreditScore                     int64
EmploymentStatus               object
EducationLevel                 object
Experience                      int64
LoanAmount                      int64
LoanDuration                    int64
MaritalStatus                  object
NumberOfDependents              int64
HomeOwnershipStatus            object
MonthlyDebtPayments             int64
CreditCardUtilizationRate     float64
NumberOfOpenCreditLines         int64
NumberOfCreditInquiries         int64
DebtToIncomeRatio             float64
BankruptcyHistory              object
LoanPurpose                    object
PreviousLoanDefaults            int64
PaymentHistory                  int64
LengthOfCreditHistory           int64
SavingsAccountBalance         float64
CheckingAccountBalance          int64
TotalAssets                     int64
TotalLiabilities                int64
MonthlyIncome                 float64
UtilityBillsPaymentHistory    float64
JobTenure                       int64
NetWorth                        int64
BaseInterestRate              float64
InterestRate                  float64
MonthlyLoanPayment            float64
TotalDebtToIncomeRatio        float64
LoanApproved                    int64
RiskScore                     float64
dtype: object

In [10]:
# Check dataset size
print(df.shape)

(20000, 35)

In [ ]:
# EDA Code Here - Create New Cells As Needed
None

## Data Preparation
5. Design your preprocessing strategy:
- Create separate preprocessing flows for different feature types
- Must utilize ColumnTransformer and Pipeline
- Consider using FeatureUnion as well
- Handle missing values appropriately for each feature
- Handle Categorical and Ordinal data appropriately
- Scale numeric values if model requires it (linear model)
- Document your reasoning for each preprocessing decision

In [ ]:
# Data Prep Code Here - Create New Cells As Needed
None

## Modeling
6. Implement your modeling approach:
- Choose appropriate model algorithms based on your problem definition
- Set up validation strategy with chosen metrics
- Use a train test split and cross validation
- Create complete pipeline including any preprocessing and model
- Document your reasoning for each modeling decision

7. Optimize your model:
- Define parameter grid based on your understanding of the algorithms
- Implement GridSearchCV and/or RandomizedSearchCV with chosen metrics
- Consider tuning preprocessing steps
- Track and document the impact of different parameter combinations
- Consider the trade-offs between different model configurations

NOTE: Be mindful of time considerations - showcase “how to tune”

In [ ]:
#  Modeling Code Here - Create New Cells as Needed
None

## Evaluation and Conclusion
8. Conduct thorough evaluation of final model:
- Assess models test data performance using your defined metrics
- Analyze performance across different data segments
- Identify potential biases or limitations
- Visualize model performance
    - Classification: Confusion Matrix/ROC-AUC
    - Regression: Scatter Plot (Predicted vs. Actual values)

9. Extract and interpret feature importance/significance:
- Which features had the most impact on your model?
- Does this lead to any potential business recommendations?

10. Prepare your final deliverable:
- Technical notebook with complete analysis
- Executive summary for business stakeholders
- Recommendations for implementation
- Documentation of potential improvements